name: check

on:
  push:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  pull_request:
    branches:
      - "**"
    paths:
      - ".github/workflows/check.yml"
      - "assets/**"
      - "**.py"
      - "pyproject.toml"
      - "uv.lock"
  workflow_dispatch:

jobs:
  resource:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'npm'

      - name: Run maa-checker
        run: |
          npm ci
          npx @nekosu/maa-tools check

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Setup uv
        uses: astral-sh/setup-uv@v9.0.0

      - name: Validate JSON Schema
        run: |
          uv run --frozen --only-group schema python tools/validate_schema.py --resource-dirs assets/resource --exclude-dirs assets/resource/announcement --interface-files assets/interface.json
