name: PNG Image Optimization

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *" # UTC+8 04:00

permissions:
  contents: write

jobs:
  optimize-png:
    name: Optimize PNG Images
    # Only run on main repo, skip bot commits to prevent infinite loops
    if: >-
      ${{ github.actor != 'github-actions[bot]' &&
          github.triggering_actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          show-progress: false

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Setup oxipng
        uses: baptiste0928/cargo-install@v3
        with:
          crate: oxipng

      - name: Optimize png images
        run: |
          python3 tools/optimize_templates/optimize_templates.py

      - name: Commit and push changes
        uses: actions-js/push@master
        with:
          rebase: true
          branch: ${{ github.ref }}
          message: "chore: 自动优化图片模板

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

            [skip changelog]"
          github_token: ${{ secrets.GITHUB_TOKEN }}
